config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :page_carousel_slides
  resources :carousel_slides
  resources :pages
  resources :comm_groups
  resources :collections do
    collection do
      # special route to get collection id number from uid_controller.js
      get 'find_by_name'
    end
  end
  resources :people
  resources :archive_items, only: [:index, :create, :show, :new, :edit, :destroy, :update, ] do
    collection do
      post :export_to_csv
    end
    member do
      patch :update_content_files_order
      patch :update_medium_photos_order
      get 'copy'
      delete 'delete_medium_photo'
      delete 'delete_poster_image'
      delete 'delete_content_file'
      get :create_uid_pdf
      get :content_files_list
    end
  end
  resources :archive_tags
  resources :locations
  get '/archive_items/sync_search' => 'archive_items#sync_search_strings';

  devise_for :users, :controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions' }
  resources :users, only: [:index]

  namespace :api do
    namespace :v1 do
      get 'archive_items/search'
      get 'archive_items/index'
      get 'archive_items/page_count'
      get 'archive_items/search_page_count'
      get 'archive_items/pages_index'
      get 'archive_items/timeline'
      get '/archive_items/:id', to: 'archive_items#show'
      get 'pages/index'
      get '/pages/:slug', to: 'pages#show'
      get 'locations/index'
      get 'locations/:name', to: 'locations#show'
      get 'tags/index'
      get 'comm_groups/index'
      get 'people/index'
      get 'carousel_slides/index'
      get 'collections/index'
      get 'page_carousel_slides/index'
      post 'comments', to: 'comments#create'
    end
  end
  root :to => 'archive_items#index'
  # root 'homepage#index'

  get '*all', to: 'archive_items#index', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/collection.rb
class Collection < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
  ["created_by", "name", "updated_by"]
  end

  # special concatenation for instantiation UID and UID UI in ArchiveItem#new
  def id_and_name
    "#{id}_#{name}"
  end
end

app/controllers/api/v1/collections_controller.rb
class Api::V1::CollectionsController < ApplicationController
  include ActiveStorage::SetCurrent
  def index
    collections = Collection.all.order(name: :asc)
    render json: collections
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :index]
  before_action :set_collection, only: %i[ show edit update destroy ]
  PAGE_ITEMS = 25

  def find_by_name
    @collection = Collection.find_by(name: params[:name])
    if @collection
      render json: {id: @collection.id}
    else
      render json: {error: "Collection not found"}, status: :not_found
    end
  end

  # GET /collections or /collections.json
  def index
    if params[:archive_q]
      @pagy, @collections = pagy(Collection.ransack(name_cont: params[:archive_q]).result, page: params[:page], items: PAGE_ITEMS)
    else
      @pagy, @collections = pagy(Collection.all.order(name: :asc), page: params[:page], items: PAGE_ITEMS)
    end
  end

  # GET /collections/1 or /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
    @submit_text = "Add Collection"
    @current_user = current_user
  end

  # GET /collections/1/edit
  def edit
    @submit_text = "Update Collection"
    @current_user = current_user
  end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collections_path, notice: "Collection was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    old_name = @collection.name

    respond_to do |format|
      if @collection.update(collection_params)
        # this iterator updates search strings of all archive item instances tagged with this @collection, necessary bc acts_as_ordered_taggable_on abstracts archive item instances from collection instances
        ArchiveItem.tagged_with(old_name, :on => :collections).each do |item|
          item.collection_list.remove(old_name)
          item.collection_list.add(@collection.name)
          item.update_columns(search_collections: item.collection_list.join(', '))
          item.save
        end
        format.html { redirect_to collections_path, notice: "Collection was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:name, :created_by, :updated_by)
    end
end

app/views/collections/_form.html.erb
<%= form_with( model: [@collection], html: { class: "admin-form" }) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-set">
      <%= form.label :name, "Name" %>
      <%= form.text_field :name, autocomplete: "off", "data-lpignore": true %>
    </div>
    <div class="form-set"></div>
  </div>

  <% if action_name == "new" %>
    <%= form.hidden_field :created_by, value: @current_user.email %>
  <% else %>
    <%= form.hidden_field :updated_by, value: @current_user.email %>
    <div class="form-row">
      <div class="form-set">
        <%= form.label :created_by, "Added by" %>
        <%= form.text_field :created_by, disabled: true %>
      </div>
      <div class="form-set">
        <%= form.label :created_at, "Date added" %>
        <input disabled="disabled" type="text" value=<%= @collection.created_at.strftime("%-m/%-d/%Y") %> />
      </div>
    </div>
  <% end %>

  <% if @collection.updated_by %>
    <div class="form-row">
      <div class="form-set">
        <%= form.label :updated_by, "Last updated by" %>
        <%= form.text_field :updated_by, disabled: true %>
      </div>
      <div class="form-set">
        <%= form.label :updated_at, "Date updated" %>
        <input disabled="disabled" type="text" value=<%= @collection.updated_at.strftime("%-m/%-d/%Y") %> />
      </div>
    </div>
  <% end %>

  <% if notice || alert %>
    <div class="err-messages">
      <div class="notice"><%= notice %></div>
      <div class="alert"><%= alert %></div>
    </div>
  <% end %>
  
  <div class="form-set form-controls">
    <%= form.submit @submit_text, class: "button-round" %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<div class="admin-breadcrumbs"><%= link_to "Collections", collections_path %> &#8250; <span>Edit a collection</span></div>
<h1 class="admin-heading">Edit a collection</h1>

<%= render 'form', collection: @collection %>

app/views/collections/index.html.erb
<% if notice || alert %>
  <div class="err-messages">
    <% if notice %>
      <div class="notice"><%= notice %></div>
    <% elsif alert %>
      <div class="alert"><%= alert %></div>
    <% end %>
  </div>
<% end %>

<div class="admin-heading-wrapper --has-search">
  <h1 class="admin-heading">Collections</h1>
  <%= link_to "Add a collection", new_collection_path, class: "button-round  --secondary" %>

  <%= form_with url: url_for(action: 'index', controller: 'collections'), html: {class: "search__form"}, method: :get do |form| %>
    <div class="search__input-wrapper">
      <%= form.text_field :archive_q, class: "search__field--round", value: params[:archive_q] %>
      <% if params[:archive_q] %>
        <button type="button" class="search__clear js-search-clear" data-clear-path="/collections"></button>
      <% end %>
    </div>
    <%= form.submit "Search", class: "search__button--round" %>
  <% end %>
</div>

<table class="admin-table">
  <thead>
    <tr>
        <th>Name</th>
        <th></th>
    </tr>
  </thead>
  <tbody>
  <% @collections.each do |collection| %>
    <tr>
      <td><%= collection.name %></td>
      <td class="admin-table-actions">
        <%= button_to 'Edit', edit_collection_path(collection), method: 'get', class: "admin-table-button"%>
        <%= button_to 'Remove', collection_path(collection), method: 'delete', data: { confirm: 'Are you sure?' }, class: "admin-table-button" %>
      </td>
  <% end %>
  </tbody>
</table>

<div class="pagination-container">
  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>

  <%= form_with url: url_for(action: 'index', controller: 'collections'), method: :get, html: {id: 'page-items-form', class: 'pagy-nav'} do |form| %>
    <%= form.label :page_items, "Items per page:" %>
    <%= form.select :page_items, options_for_select([25, 50, 100], params[:page_items].to_i), {}, { class: 'items-select',onchange: 'this.form.submit()'} %>
  <% end %>
</div>

app/views/collections/new.html.erb
<div class="admin-breadcrumbs"><%= link_to "Collections", collections_path %> &#8250; <span>Add a collection</span></div>
<h1 class="admin-heading">Add a collection</h1>

<%= render 'form', collection: @collection %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<%= link_to 'Edit', edit_admin_collection_path(@collection) %> |
<%= link_to 'Back', admin_collections_path %>