config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :page_carousel_slides
  resources :carousel_slides
  resources :pages
  resources :comm_groups
  resources :collections do
    collection do
      # special route to get collection id number from uid_controller.js
      get 'find_by_name'
    end
  end
  resources :people
  resources :archive_items, only: [:index, :create, :show, :new, :edit, :destroy, :update, ] do
    collection do
      post :export_to_csv
    end
    member do
      patch :update_content_files_order
      patch :update_medium_photos_order
      get 'copy'
      delete 'delete_medium_photo'
      delete 'delete_poster_image'
      delete 'delete_content_file'
      get :create_uid_pdf
      get :content_files_list
    end
  end
  resources :archive_tags
  resources :locations
  get '/archive_items/sync_search' => 'archive_items#sync_search_strings';

  devise_for :users, :controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions' }
  resources :users, only: [:index]

  namespace :api do
    namespace :v1 do
      get 'archive_items/search'
      get 'archive_items/index'
      get 'archive_items/page_count'
      get 'archive_items/search_page_count'
      get 'archive_items/pages_index'
      get 'archive_items/timeline'
      get '/archive_items/:id', to: 'archive_items#show'
      get 'pages/index'
      get '/pages/:slug', to: 'pages#show'
      get 'locations/index'
      get 'locations/:name', to: 'locations#show'
      get 'tags/index'
      get 'comm_groups/index'
      get 'people/index'
      get 'carousel_slides/index'
      get 'collections/index'
      get 'page_carousel_slides/index'
      post 'comments', to: 'comments#create'
    end
  end
  root :to => 'archive_items#index'
  # root 'homepage#index'

  get '*all', to: 'archive_items#index', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/archive_item.rb
require 'csv'

class ArchiveItem < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search_archive_items,
        against: {
            title: 'A',
            search_people: 'B',
            search_comm_groups: 'B',
            search_tags: 'C',
            search_locations: 'C',
            search_collections: 'D'
    },
        using: {
            tsearch: {
                dictionary: 'english', tsvector_column: 'ft_search'
            }
    }

    pg_search_scope :search_cms_archive_items,
        against: {
            title: 'A',
            search_people: 'B',
            search_comm_groups: 'B',
            search_tags: 'C',
            search_locations: 'C',
            search_collections: 'D',
            created_by: 'D',
            updated_by: 'D',
            redirect_links: 'D'
    },
        using: {
            tsearch: {
                dictionary: 'english', tsvector_column: 'cms_ft_search'
            }
    }

    # has_one_attached :content_file
    has_many :redirect_links, dependent: :destroy, inverse_of: :archive_item
    accepts_nested_attributes_for :redirect_links, allow_destroy: true
    has_many_attached :content_files
    has_one_attached :medium_photo
    has_many_attached :medium_photos
    acts_as_ordered_taggable
    acts_as_ordered_taggable_on :tags, :locations, :people, :comm_groups, :collections
    has_rich_text :content_notes
    has_rich_text :medium_notes
    has_one_attached :poster_image

    def ordered_content_files
        return content_files unless content_files_order.present?

        ids = content_files_order.map(&:to_s)
        content_files.sort_by { |f| ids.index(f.id.to_s) || ids.length }
    end

    def ordered_medium_photos
        return medium_photos unless medium_photos_order.present?

        ids = medium_photos_order.map(&:to_s)
        medium_photos.sort_by { |f| ids.index(f.id.to_s) || ids.length }
    end

    # validations
    validates :medium, presence: true, inclusion: { in: ["photo","film","audio","article","printed material"] }
    # validates :collections, presence: true

    before_validation :strip_title, on: [:create, :update]
    # sets uid upon record creation, update
    after_commit :set_uid!, on: [:create, :update]

    # this method copies the taggable 'metadata' from on archive_item to the form for a new one
    def copy_tags_from(other_item)
        %i[tag location person comm_group collection].each do |metadata|
        tag_list = other_item.send("#{metadata.to_s}_list")
        tag_list_string = tag_list.join(", ")
        self.send("#{metadata.to_s}_list=", tag_list_string)
        end
    end

    private

    MEDIUM_CODES = {
        "photo" => 1,
        "film" => 2,
        "audio" => 3,
        "article" => 4,
        "printed material" => 5
    }.freeze

    # method for setting UID upon record creation
    # UID is set here, because including record ID in #new UI, requires manipulating values in real time
    def set_uid!
        return if collection_list.blank? || medium.blank?
        coll = Collection.find_by(name: collection_list.first)
        coll_id = coll.id
        medium_code = MEDIUM_CODES[medium]

        # pad id values with 0's
        coll_str = format('%03d', coll_id)
        medium_str = format('%03d', medium_code)
        item_str = format('%06d', id)

        # halve item string for 3rd hyphen
        part1, part2 = item_str[0, 3], item_str[3, 3]

        update_column(:uid, "#{coll_str}-#{medium_str}-#{part1}-#{part2}")
    end

    def strip_title
        self.title = title.to_s.strip
    end
end

app/controllers/api/v1/archive_items_controller.rb
class Api::V1::ArchiveItemsController < ApplicationController
  include ActiveStorage::SetCurrent
  include Rails.application.routes.url_helpers
  def index
    archive_items = base_scope
    archive_items = filter_tags(archive_items)
    archive_items = filter_medium_and_year(archive_items)
    archive_items = archive_items.order(featured_item: :desc, updated_at: :desc)
    render json: archive_items
  end

  def page_count
    archive_items = base_scope
    archive_items = filter_tags(archive_items)
    archive_items = filter_medium_and_year(archive_items, paginate: false)

    render json: archive_items.count
  end

  def pages_index
    archive_items = base_scope.tagged_with(params[:page_tags], :any => true)
    archive_items = filter_tags(archive_items)
    archive_items = filter_medium_and_year(archive_items).order(featured_item: :desc, updated_at: :desc)

    render json: archive_items
  end

  def timeline
    cache_key = "timeline/#{params[:page_tags]}"

    timeline_items = ArchiveItem
                    .select(:id, :year, :title, :date_is_approx, :medium)
                    .where(draft: false)
                    .tagged_with(params[:page_tags], :any => true)
                    .merge(ArchiveItem.where.not(year: nil))
                    .with_attached_poster_image
                    .with_attached_medium_photos
                    .with_attached_content_files
                    .order(year: :asc)

     items_as_json = Rails.cache.fetch(cache_key, expires_in: 4.hours ) do
      timeline_items.map do |item|
        {
          id: item.id,
          year: item.year,
          title: item.title,
          date_is_approx: item.date_is_approx,
          medium: item.medium,
          poster_image_url: item.poster_image.attached? ? item.poster_image.url() : nil,
          medium_photo_url: item.medium_photos.attached? ? item.medium_photos[0].url() : nil,
          content_file_url: item.content_files.attached? ? item.content_files[0].url() : nil,
          time: Time.current
        }
      end
    end

    render json: items_as_json
  end

  def search
    archive_items = search_scope
    archive_items = filter_medium_and_year(archive_items)

    render json: archive_items
  end

  def search_page_count
    archive_items = search_scope
    archive_items = filter_medium_and_year(archive_items)

    render json: archive_items.count
  end

  def show
    if archive_item
      render json: archive_item
    else
      render json: archive_item.errors
    end
  end

  private

  def base_scope
    ArchiveItem.where(draft: false)
  end

  def array_param(key)
    Array(params[key]).reject(&:blank?)
  end

  def filter_tags(archive_items)
    allTags = params.slice(:tags, :locations, :comm_groups, :people, :collections).values.flatten.compact
    allTags.length > 0 ? archive_items.tagged_with(allTags, :any => true) : archive_items
  end

  def filter_medium_and_year(scope, paginate: true)
    years = array_param(:year).map(&:to_i)
    media = array_param(:medium)

    if years.any?
      year_ranges = years.map{ |y| y..(y + 9)}

      sql = year_ranges.map {"(year BETWEEN ? AND ?)"}.join("OR")
      bindings = year_ranges.flat_map { |r| [r.begin, r.end] }

      scope = scope.where(sql, *bindings)
    end

    if media.any?
      scope = scope.where(medium: media)
    end

    paginate ? scope.offset(params[:offset]).limit(params[:limit]) : scope
  end

  def search_scope
  # get items with matching tags
    if params[:page_tags] && params[:page_tags].join.empty?
      tag_archive_items = base_scope.tagged_with(params[:page_tags], :on => :tags, :any => true).search_archive_items(params[:q])
    end

    # get items with matching collections
    if params[:page_collections] && params[:page_collections].join.empty?
      collection_archive_items = base_scope.tagged_with(params[:page_collections], :on => :collections, :any => true).search_archive_items(params[:q])
    end

    archive_items =
      if tag_archive_items && collection_archive_items
        # if both item and collection items exist, combine them
        tag_archive_items.or(collection_archive_items)
      elsif tag_archive_items
        # if only one exists, use that
        filter_tags(tag_archive_items)
      elsif collection_archive_items
        filter_tags(collection_archive_items)
      else
        # if none of the above conditions are met, just search for items
        base_scope.search_archive_items(params[:q])
      end

      filter_tags(archive_items)
  end

  def archive_item
    @archive_item ||= ArchiveItem.where(draft: false).find(params[:id])
  end
end

app/helpers/archive_items_helper.rb
module ArchiveItemsHelper
  def sort_link(label, base, items, default_dir: :asc)
    current = params[:sort].to_s
    asc_key = base
    desc_key = "#{base}-desc"

    next_key =
      if current == asc_key
        desc_key
      elsif current == desc_key
        asc_key
      else
        default_dir == :desc ? desc_key : asc_key
      end

    css =
      if current == asc_key
        'sorted-down'
      elsif current == desc_key
        'sorted-up'
      end

      base_url = request.query_parameters.except(:page)

    link_to label,
      archive_items_path(base_url.merge(:sort => next_key, :page_items => items, page: nil)),
      class: css
  end

  def flagged_link
    if params[:sort] =='flagged'
      link_to 'Show All Archive Items',
        archive_items_path,
        class: 'table-header-button'
    else
      link_to 'Show Only Archive Items Missing Files',
        archive_items_path(request.query_parameters.merge(sort: 'flagged', page: nil)),
        class: 'table-header-button'
    end
  end
end

app/views/archive_items/_content_files_list.html.erb
<div id="content-files-list">
  <ul
    id="content-files-list-el"
    data-controller="sortable"
    <% if @archive_item.persisted? %>
      data-sortable-url-value="<%= update_content_files_order_archive_item_path(@archive_item) %>"
      data-sortable-hidden-input-value="#content-files-order"
    <% end %>
  >
    <% if @archive_item.persisted? &&  @archive_item.content_files.attached? %>
      <% @archive_item.ordered_content_files.each do |file| %>
        <li data-id="<%= file.id %>" class="preview-thumbs">
          <% if file.content_type == "image/jpeg" || file.content_type == "image/png" %>
            <div class="removable-image-container">
              <%= link_to 'X Remove File', delete_content_file_archive_item_path(@archive_item, content_file_id: file.id), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "clear_one_attachment_button" %>
              <%= image_tag file.variant(resize_to_limit: [600, nil]), class: "admin-form-image" %>
            </div>
          <% else %>
            <div class="no-thumbnail-content-file">
              <%= link_to "View #{file.blob.filename}", file, target: "_blank", class: "download-link" %>
              <%= link_to 'X Remove File', delete_content_file_archive_item_path(@archive_item, content_file_id: file.id), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "delete-file-link" %>
            </div>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <% if @archive_item.persisted? %>
    <%= hidden_field_tag "archive_item[content_files_order]", "", id: "content-files-order" %>
  <% end %>

  <div
    class="upload-container"
    data-controller="dropzone"
    data-upload-multiple="true"
  >
    <%=
      file_field_tag "archive_item[content_files][]",
      multiple: true,
      direct_upload: true,
      id: "content-files-input",
      data: { dropzone_target: "input" }
    %>
    <div class="dropzone">Drop files here or click to upload</div>
    <div
      data-dropzone-target="previewsContainer"
      class="previews-container"
    ></div>
  </div>
</div>

app/views/archive_items/_medium_photos_list.html.erb
<div id="medium-photos-list">
  <ul
    data-controller="sortable"
    <% if @archive_item.persisted? %>
      data-sortable-url-value="<%= update_medium_photos_order_archive_item_path(@archive_item) %>"
      data-sortable-hidden-input-value="#medium-photos-order"
    <% end %>
  >
    <% if @archive_item.persisted? && @archive_item.medium_photos.attached? %>
      <% @archive_item.ordered_medium_photos.each do |file| %>
        <li data-id="<%= file.id %>" class="preview-thumbs">
          <% if file.content_type == "image/jpeg" || file.content_type == "image/png" %>
            <div class="removable-image-container">
              <%= link_to 'X Remove File', delete_medium_photo_archive_item_path(@archive_item, medium_photo_id: file.id), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "clear_one_attachment_button" %>
              <%= image_tag file.variant(resize_to_limit: [600, nil]), class: "admin-form-image" %>
            </div>
          <% else %>
            <div class="no-thumbnail-content-file">
              <%= link_to 'View photo', file, target: "_blank", class: "download-link" %>
              <%= link_to 'X Remove File', delete_medium_photo_archive_item_path(@archive_item, medium_photo_id: file.id), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "delete-file-link" %>
            </div>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <% if @archive_item.persisted? %>
    <%= hidden_field_tag "archive_item[medium_photos_order]", "", id: "medium-photos-order" %>
  <% end %>

  <div
    class="upload-container"
    data-controller="dropzone"
    data-upload-multiple="true"
    data-dropzone-accepted-files="image/*"
  >
    <%=
      file_field_tag "archive_item[medium_photos][]",
      multiple: true,
      direct_upload: true,
      id: "medium-photos-input",
      data: { dropzone_target: "input" }
    %>
    <div class="dropzone">Drop photos here or click to upload</div>
    <div
      data-dropzone-target="previewsContainer"
      class="previews-container"
    ></div>
  </div>
</div>

app/views/archive_items/_redirect_links.html.erb
<div class="link-row" data-draft="<%= [:draft] ? 'true' : 'false' %>" data-redirect-links-target="row">
  <div class="form-row">
    <div class="grabber-div"><%= render_svg 'grabber', classes: "grabber" %></div>
    <div class="form-set">
      <%= f.label :url_label, "Link text" %>
      <%= f.text_field :url_label, placeholder: "e.g. Project homepage" %>
    </div>
    <div class="form-set">
      <%= f.label :url, "URL" %>
      <%= f.url_field :url, placeholder: "https://example.com" %>
    </div>
    <%= f.hidden_field :position, value: f.object.position || 9999 %>
    <div class="form-set remove_redirect-set">
      <button
        type="button"
        class="button-round redirect_x-button"
        data-redirect-links-target="del"
        data-action="redirect-links#remove"
      >X</button>
      <%= f.check_box :_destroy, style: "display:none" %>
    </div>
  </div>
</div>

app/views/archive_items/copy.html.erb
<div class="admin-breadcrumbs"><%= link_to "Archive Items", archive_items_path %> &#8250; <span>Create an item</span></div>
<h1 class="admin-heading">Create an item</h1>
<%= render "form" %>

app/views/archive_items/edit.html.erb
<div class="admin-breadcrumbs"><%= link_to "Archive Items", archive_items_path %> &#8250; <span>Update item</span></div>
<h1 class="admin-heading">Update item</h1>
<%= render "form" %>

app/views/archive_items/index.html.erb
<% if notice || alert %>
  <div class="err-messages">
    <% if notice %>
      <div class="notice"><%= notice %></div>
    <% elsif alert %>
      <div class="alert"><%= alert %></div>
    <% end %>
  </div>
<% end %>

<div class="admin-heading-wrapper --has-search">
  <h1 class="admin-heading">Archive Items (<%= number_with_delimiter(@total_item_count, :delimiter => ',') %>) </h1>
  <%= link_to "Add an item", new_archive_item_path, class: "button-round --secondary" %>

  <%= form_with url: url_for(action: 'index', controller: 'archive_items'), html: {class: "search__form"}, method: :get do |form| %>
    <div class="search__input-wrapper">
      <%= form.text_field :archive_q, class: "search__field--round", value: params[:archive_q] %>
      <% if params[:archive_q] %>
        <button type="button" class="search__clear js-search-clear" data-clear-path="/admin/archive_items"></button>
      <% end %>
    </div>
    <%= form.submit "Search", class: "search__button--round" %>
  <% end %>
</div>

<table class="admin-table">
  <thead>
    <tr>
        <th><%= sort_link('Subject', 'subject', @pagy.items) %></th>
        <th><%= sort_link( 'Draft/Published', 'draft', @pagy.items) %></th>
        <th>UID</th>
        <th><%= sort_link( 'Collection', 'collection', @pagy.items) %></th>
        <th><%= sort_link( 'Medium', 'medium', @pagy.items) %></th>
        <th><%= sort_link( 'Year', 'year', @pagy.items) %></th>
        <th><%= sort_link( 'Last edited', 'edited', @pagy.items) %></th>
        <th><%= flagged_link %></th>
        <th><%= sort_link( 'File Type', 'file_type', @pagy.items) %></th>
        <th></th>
    </tr>
  </thead>
  <tbody>
  <% @archive_items.each do |archive_item| %>
    <tr>
      <td><%= archive_item.title %></td>
      <td>
        <% if archive_item.draft %>
          <div class="light draft">DRAFT</div>
        <% elsif !archive_item.draft %>
          <div class="light published">PUBLISHED</div>
        <% end %>
      </td>
      <td>
        <% if archive_item.uid.present? %>
          <%= link_to archive_item.uid, create_uid_pdf_archive_item_path(archive_item), method: 'get', class: "admin-table-button", target: '_blank'  %>
        <% else %>
          <%= '' %>
        <% end %>
      </td>
      <td><%= archive_item.search_collections %></td>
      <td><%= archive_item.medium %></td>
      <td><%= archive_item.year %></td>
      <td><%= archive_item.updated_at.strftime("%-m/%-d/%Y") %></td>
      <td >
        <div class="flag">
          <% if !archive_item.content_files.attached? && !archive_item.content_redirect  %>
              <%= image_tag('flag-icon-red.svg') %>  <span>Missing media files!</span>
          <% end %>
        </div>
      </td>
      <td>
        <% if archive_item.content_files.attached? %>
          <%= archive_item.content_files[0].blob.content_type %>
        <% else %>
          No content files
        <% end %>
      </td>
      <td class="admin-table-actions">
        <%= button_to 'Edit •', edit_archive_item_path(archive_item), method: 'get', class: "admin-table-button"%>
        <%= button_to 'Remove •', archive_item_path(archive_item), method: 'delete', data: { confirm: 'Are you sure?' }, class: "admin-table-button" %>
        <%= button_to 'Copy Metadata to New Item •', copy_archive_item_path(archive_item), method: 'get', class: "admin-table-button"%>
      </td>
  <% end %>
  </tbody>
</table>

<div class="pagination-container">
  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>

  <%= button_to "Export CSV Snapshot", export_to_csv_archive_items_path, class: "button-round sml"  %>

  <%= form_with url: url_for(action: 'index', controller: 'archive_items'), method: :get, html: {id: 'page-items-form', class: 'pagy-nav'} do |form| %>
    <%= form.label :page_items, "Items per page:" %>
    <%= form.select :page_items, options_for_select([25, 50, 100], params[:page_items].to_i), {}, { class: 'items-select',onchange: 'this.form.submit()'} %>
  <% end %>
</div>

app/views/archive_items/new.html.erb
<div class="admin-breadcrumbs"><%= link_to "Archive Items", archive_items_path %> &#8250; <span>Create an item</span></div>
<h1 class="admin-heading">Create an item</h1>
<%= render "form" %>