config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :page_carousel_slides
  resources :carousel_slides
  resources :pages
  resources :comm_groups
  resources :collections do
    collection do
      # special route to get collection id number from uid_controller.js
      get 'find_by_name'
    end
  end
  resources :people
  resources :archive_items, only: [:index, :create, :show, :new, :edit, :destroy, :update, ] do
    collection do
      post :export_to_csv
    end
    member do
      patch :update_content_files_order
      patch :update_medium_photos_order
      get 'copy'
      delete 'delete_medium_photo'
      delete 'delete_poster_image'
      delete 'delete_content_file'
      get :create_uid_pdf
      get :content_files_list
    end
  end
  resources :archive_tags
  resources :locations
  get '/archive_items/sync_search' => 'archive_items#sync_search_strings';

  devise_for :users, :controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions' }
  resources :users, only: [:index]

  namespace :api do
    namespace :v1 do
      get 'archive_items/search'
      get 'archive_items/index'
      get 'archive_items/page_count'
      get 'archive_items/search_page_count'
      get 'archive_items/pages_index'
      get 'archive_items/timeline'
      get '/archive_items/:id', to: 'archive_items#show'
      get 'pages/index'
      get '/pages/:slug', to: 'pages#show'
      get 'locations/index'
      get 'locations/:name', to: 'locations#show'
      get 'tags/index'
      get 'comm_groups/index'
      get 'people/index'
      get 'carousel_slides/index'
      get 'collections/index'
      get 'page_carousel_slides/index'
      post 'comments', to: 'comments#create'
    end
  end
  root :to => 'archive_items#index'
  # root 'homepage#index'

  get '*all', to: 'archive_items#index', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/carousel_slide.rb
class CarouselSlide < ApplicationRecord
    has_one_attached :image
end

app/controllers/api/v1/carousel_slides_controller.rb
class Api::V1::CarouselSlidesController < ApplicationController
  include ActiveStorage::SetCurrent
  def index
    slides = CarouselSlide.all.order(position: :asc)
    render json: slides
  end
end

app/controllers/carousel_slides_controller.rb
class CarouselSlidesController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!
  before_action :set_carousel_slide, only: %i[ show edit update destroy ]

  # GET /carousel_slides or /carousel_slides.json
  def index
    @carousel_slides = CarouselSlide.all.order(position: :asc)
  end

  # GET /carousel_slides/1 or /carousel_slides/1.json
  def show
  end

  # GET /carousel_slides/new
  def new
    @pages_options = Page.all.order(title: :asc).pluck(:title, :slug)
    @carousel_slide = CarouselSlide.new
  end

  # GET /carousel_slides/1/edit
  def edit
    @pages_options = Page.all.order(title: :asc).pluck(:title, :slug)
  end

  # POST /carousel_slides or /carousel_slides.json
  def create
    @carousel_slide = CarouselSlide.new(carousel_slide_params)

    respond_to do |format|
      if @carousel_slide.save
        format.html { redirect_to carousel_slides_url, notice: "Carousel slide was successfully created." }
        format.json { render :show, status: :created, location: @carousel_slide }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carousel_slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carousel_slides/1 or /carousel_slides/1.json
  def update
    respond_to do |format|
      if @carousel_slide.update(carousel_slide_params)
        format.html { redirect_to carousel_slides_url, notice: "Carousel slide was successfully updated." }
        format.json { render :show, status: :ok, location: @carousel_slide }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carousel_slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carousel_slides/1 or /carousel_slides/1.json
  def destroy
    @carousel_slide.destroy
    respond_to do |format|
      format.html { redirect_to carousel_slides_url, notice: "Carousel slide was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carousel_slide
      @carousel_slide = CarouselSlide.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def carousel_slide_params
      params.require(:carousel_slide).permit(:title, :description, :link, :image, :position)
    end
end

app/views/carousel_slides/_form.html.erb
<%= form_with( model: [@carousel_slide], html: { class: "admin-form" }, data: { controller: 'direct-uploads' } ) do |form| %>
  <% if carousel_slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carousel_slide.errors.count, "error") %> prohibited this carousel_slide from being saved:</h2>

      <ul>
        <% carousel_slide.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-set">
      <%= form.label :title, "Title" %>
      <%= form.text_field :title, autocomplete: "off", "data-lpignore": true %>
    </div>
    <div class="form-set"></div>
  </div>

  <div class="form-row">
    <div class="form-set">
      <%= form.label :position, "Position" %>
      <%= form.number_field :position, autocomplete: "off", "data-lpignore": true %>
    </div>
    <div class="form-set"></div>
  </div>

  <div class="form-row">
    <% if carousel_slide.image.attached? %>
      <div class="form-set">
        <label>Image Preview</label>
        <% if carousel_slide.image.content_type == "image/jpeg" || carousel_slide.image.content_type == "image/png" %>
          <div class="carousel-image-preview">
            <%= image_tag carousel_slide.image.variant(resize_to_limit: [1600, nil]), class: "admin-form-image carousel-image-preview-pic" %>
          </div>
        <% else %>
            <%= link_to 'View file', carousel_slide.image, target: "_blank", class: "download-link" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="form-row">
    <div class="form-set">
      <%= form.label :image, "Image" %>
      <%= form.file_field :image, direct_upload: true %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-set">
      <%= form.label :description, "Description" %>
      <%= form.text_area :description %>
    </div>
    <div class="form-set"></div>
  </div>

  <div class="form-row">
    <div class="form-set">
      <%= form.label :link, "Page to link to" %>
      <div class="form-select-wrapper">
        <%= form.select :link, @pages_options %>
      </div>
    </div>
    <div class="form-set"></div>
  </div>

  <% if notice || alert %>
    <div class="err-messages">
      <div class="notice"><%= notice %></div>
      <div class="alert"><%= alert %></div>
    </div>
  <% end %>

  <div class="form-set form-controls">
    <%= form.submit "Save", class: "button-round" %>
  </div>
<% end %>

app/views/carousel_slides/edit.html.erb
<div class="admin-breadcrumbs"><%= link_to "Carousel slides", carousel_slides_path %> &#8250; <span>Edit a slide</span></div>
<h1 class="admin-heading">Edit a slide</h1>

<%= render 'form', carousel_slide: @carousel_slide %>

app/views/carousel_slides/index.html.erb
<% if notice || alert %>
  <div class="err-messages">
    <% if notice %>
      <div class="notice"><%= notice %></div>
    <% elsif alert %>
      <div class="alert"><%= alert %></div>
    <% end %>
  </div>
<% end %>

<div class="admin-heading-wrapper">
  <h1 class="admin-heading">Carousel Slides</h1>
  <%= link_to "Add a slide", new_carousel_slide_path, class: "button-round  --secondary" %>
</div>

<table class="admin-table">
  <thead>
    <tr>
        <th>Title</th>
        <th></th>
    </tr>
  </thead>
  <tbody>
  <% @carousel_slides.each do |slide| %>
    <tr>
      <td><%= slide.title %></td>
      <td class="admin-table-actions">
        <%= button_to 'Edit', edit_carousel_slide_path(slide), method: 'get', class: "admin-table-button"%>
        <%= button_to 'Remove', carousel_slide_path(slide), method: 'delete', data: { confirm: 'Are you sure?' }, class: "admin-table-button" %>
      </td>
  <% end %>
  </tbody>
</table>

app/views/carousel_slides/new.html.erb
<div class="admin-breadcrumbs"><%= link_to "Carousel slides", carousel_slides_path %> &#8250; <span>Create a slide</span></div>
<h1 class="admin-heading">Create a slide</h1>

<%= render 'form', carousel_slide: @carousel_slide %>

app/views/carousel_slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @carousel_slide.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @carousel_slide.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @carousel_slide.link %>
</p>

<%= link_to 'Edit', edit_admin_carousel_slide_path(@carousel_slide) %> |
<%= link_to 'Back', admin_carousel_slides_path %>